import '../styles/globals.css'
import Navbar from './components/NavBar';
import SocialBar from "./pages/SocialBar";

export const metadata = {
    title: 'Next.js',
    desciption: 'Generated by Next.js',
}

export default function RootLayout({children}){
    return(
        <html lang='en'>
            <body>
                <Navbar/>
                <SocialBar/>
                {children}
            </body>
        </html>
    );
};